### ISSUE TITLE
"User not found" error never disappears, even after successful sharing

### ISSUE THREAD

**Issue by dlajarretie** [secretin/secretin-app#18]
If you type a wrong username when sharing a secret, the error "User not found" appears, but then it doesn't go away if you close the modal, or type a correct username.

![capture d ecran 2017-01-02 a 19 09 54](https://cloud.githubusercontent.com/assets/5681392/21594154/8d366e2c-d11f-11e6-83c8-0cfe247ee204.png)

How to reproduce :
1. On a secret, go to "who has access" tab
2. Share with a non-existing user
3. Share with an existing user

**Comment by agix** [comment]
This will fix it : https://github.com/secretin/secretin-app/pull/20/files#diff-662715a677c7c55896bdb3ef0f31f3bdR50
