### ISSUE TITLE
Urlencoding break electron local file access

### ISSUE THREAD

**Issue by matbgs** [secretin/secretin-app#31]
Blank screen after compiling windows electron app, because bad urlencoding to acces local file
![16776014_10210842535596913_487259938_o](https://cloud.githubusercontent.com/assets/3316223/22938194/4fe81812-f2db-11e6-9ed2-3996e3640704.png)

**Comment by agix** [comment]
Fixed in https://github.com/secretin/secretin-app/commit/b11cfeb4a478f8eb0cf9bb3b91740be6e3ff8e91
