### ISSUE TITLE
Change folder name

### ISSUE THREAD

**Issue by sklaxs** [secretin/secretin-app#56]
Hello, is it possible to add an option to edit folder name?

**Comment by agix** [comment]
It exists a way but it's not very UX easy :).

![step1_capture_20180522_154330](https://user-images.githubusercontent.com/2556191/40366217-e351b484-5dd6-11e8-88d3-f308fb8681cb.png)

![step_2_capture_20180522_154354](https://user-images.githubusercontent.com/2556191/40366236-f029a5a4-5dd6-11e8-92c0-056b424b20e4.png)
